<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Engine.Contracts\Engine.Contracts.csproj" />
    <ProjectReference Include="..\Engine.Core\Engine.Core.csproj" />
    <ProjectReference Include="..\Engine.Physics\Engine.Physics.csproj" />
    <ProjectReference Include="..\Engine.Runtime.Abstractions\Engine.Runtime.Abstractions.csproj" />
    <ProjectReference Include="..\Engine.Scene\Engine.Scene.csproj" />
    <ProjectReference Include="..\Engine.SceneData\Engine.SceneData.csproj" />
    <ProjectReference Include="..\Engine.Scripting\Engine.Scripting.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
